name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
    steps:
      - name: Correct env
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Check out code into the proper directory
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: ARCH=${{ matrix.arch }}
          tags: ghcr.io/${{ env.REPO }}:${{ matrix.arch }}
          platforms: linux/amd64
